# This workflow will install Python dependencies, run tests and lint with a multiple versions of Python on Linux/Mac/Windows
name: CloudFormation CLI - OS testing

on:
  push:
    branches: [ e2e-package ]

jobs:
  build:
    env:
      AWS_DEFAULT_REGION: us-east-1
    strategy:
      fail-fast: false
      matrix:
        python: [3.6, 3.7, 3.8, 3.9, "3.10"]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        pip install --upgrade 'attrs==19.2.0' wheel -r requirements.txt
    - name: Install cli
      run: |
        pip install .
        pip install --quiet cloudformation-cli-python-plugin
        wget https://github.com/aws/aws-sam-cli/releases/latest/download/AWS_SAM_CLI_64_PY3.msi -OutFile SAM.msi
        start-process msiexec.exe -Wait -ArgumentList "/I $pwd\SAM.msi /quiet"
        Start-Job -ScriptBlock{sam local start-lambda}
    - name: Run CLI switches
      run: |
        mkdir test
        cd test
        cfn init -t CLI::TEST::INIT -f --artifact-type resource python37 --use-docker
        cfn validate
        cfn package
