# This workflow will install Python dependencies, run tests and lint with a multiple versions of Python on Linux/Mac/Windows
name: CloudFormation CLI - OS testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      AWS_DEFAULT_REGION: us-east-1
    strategy:
      fail-fast: false
      matrix:
        python: [3.6, 3.7, 3.8, 3.9, "3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        pip install --upgrade 'attrs==19.2.0' wheel -r requirements.txt
    - name: Install cli
      run: |
        pip install .
        pip install --quiet cloudformation-cli-python-plugin
        mkdir test
        cd test
        cfn init -t CLI::TEST::INIT -f --artifact-type resource python37 --use-docker
        cfn validate
        cfn package
